// styles.ts
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  gradient: { flex: 1 },
  container: { flex: 1 },
  contentContainer: { padding: 20, justifyContent: 'center' },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 24,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    color: '#333',
    backgroundColor: '#fff',
    marginBottom: 16,
  },
  textArea: { textAlignVertical: 'top' },
  mediaSection: { marginBottom: 16 },
  subHeader: { fontSize: 16, fontWeight: 'bold', marginBottom: 8, color: '#333' },
  mediaItemWrapper: { position: 'relative', marginRight: 8 },
  mediaImage: { width: 120, height: 80, borderRadius: 8, resizeMode: 'cover' },
  mediaVideo: { width: 120, height: 80, borderRadius: 8, backgroundColor: '#000' },
  deleteIcon: {
    position: 'absolute',
    top: 2,
    right: 2,
    backgroundColor: 'rgba(255,0,0,0.7)',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteIconText: { color: '#fff', fontSize: 12 },
  addButton: {
    width: 120,
    height: 80,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#007aff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    backgroundColor: '#e6f0ff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  addButtonText: { color: '#007aff', fontSize: 14, fontWeight: '600' },
  submitButton: {
    backgroundColor: '#007aff',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  submitButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  cancelButton: {
    backgroundColor: '#888',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 24,
  },
  cancelButtonText: { color: '#fff', fontSize: 16 },
  notice: { backgroundColor: '#f9f9f9', padding: 12, borderRadius: 8 },
  noticeText: { fontSize: 14, color: '#666', textAlign: 'center', lineHeight: 20 },
  imageViewerContainer: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullscreenImage: { width: '100%', height: '80%' },
  closeButton: { position: 'absolute', top: 40, right: 20, backgroundColor: 'rgba(0,0,0,0.6)', padding: 10, borderRadius: 20 },
  closeButtonText: { color: '#fff', fontSize: 16 },
});

export default styles;
